baseURL : https://bit-orbit.github.io/the-secret-bit
languageCode : fa-IR
title : the-secret-bit
publishDir : docs/
theme : cupper-hugo-theme/
canonifyurls : true



taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: linux command's hand-book
  homeMetaContent: the-secret-bit
  footer: Made with Love with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  #codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  logoAlt: "logo"
  customCss:
    - css/custom_01.css
  customJs:
    - js/custom_01.js


menu:
  nav:
    - name: روی جلد
      url: /
      weight: 1
    - name: مشارکت در کتاب
      url: /nav/contribute/how-to-contribute/
      weight: 2
    - name: فصل ها
      url: /posts/
      weight: 3
    - name: تگ ها
      url: /tags/
      weight: 4
    - name: انجمن
      url: https://github.com/bit-orbit/the-secret-bit/issue
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2


